# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61lculator.proto\"\x1c\n\rRequestNumber\x12\x0b\n\x03val\x18\x01 \x01(\x02\"\x1d\n\x0eResponseNumber\x12\x0b\n\x03val\x18\x01 \x01(\x02\x32;\n\nCalculator\x12-\n\nSquareRoot\x12\x0e.RequestNumber\x1a\x0f.ResponseNumberb\x06proto3'
)




_REQUESTNUMBER = _descriptor.Descriptor(
  name='RequestNumber',
  full_name='RequestNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='RequestNumber.val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=48,
)


_RESPONSENUMBER = _descriptor.Descriptor(
  name='ResponseNumber',
  full_name='ResponseNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='ResponseNumber.val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['RequestNumber'] = _REQUESTNUMBER
DESCRIPTOR.message_types_by_name['ResponseNumber'] = _RESPONSENUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestNumber = _reflection.GeneratedProtocolMessageType('RequestNumber', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTNUMBER,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:RequestNumber)
  })
_sym_db.RegisterMessage(RequestNumber)

ResponseNumber = _reflection.GeneratedProtocolMessageType('ResponseNumber', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSENUMBER,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:ResponseNumber)
  })
_sym_db.RegisterMessage(ResponseNumber)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=81,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='SquareRoot',
    full_name='Calculator.SquareRoot',
    index=0,
    containing_service=None,
    input_type=_REQUESTNUMBER,
    output_type=_RESPONSENUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
